node_cache: &node_cache
  folder: node_modules
  fingerprint_script: cat yarn.lock
  populate_script: yarn install --prefer-offline --frozen-lockfile || yarn install --frozen-lockfile

container:
  image: node:10-alpine

lint_task:
  node_modules_cache: *node_cache
  install_script: yarn install --offline --frozen-lockfile
  script: yarn run lint

test_task:
  node_modules_cache: *node_cache
  install_script: yarn install --offline --frozen-lockfile
  script: yarn run test --coverage
  container:
    matrix:
      image: node:10-alpine
      image: node:8-alpine

typecheck_task:
  node_modules_cache: *node_cache
  install_script: yarn install --offline --frozen-lockfile
  script: yarn run type:check

build_task:
  node_modules_cache: *node_cache
  install_script: yarn install --offline --frozen-lockfile
  script: yarn run build:ci
  depends_on:
    - lint
    - test
    - typecheck

deploy_task:
  depends_on:
    - build
  only_if: $BRANCH == "master"
  test_script: yarn run release
  node_modules_cache: *node_cache
