tasks:
  install:
    image: node:10
    command: ["bash", "-c"]
    args: ["yarn install --prefer-offline --pure-lockfile --frozen-lockfile || yarn install --pure-lockfile --frozen-lockfile"]
  prepare:
    image: node:10
    command:
      - yarn
    args:
      - build:execa
  lint:
    image: node:10
    command:
      - yarn
    args:
      - lint
  test:
    image: node:10
    command:
      - yarn
    args:
      - test
      - --coverage
  build:
    image: node:10
    command:
      - yarn
    args:
      - build:ci
