# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1

references:
  node-8: &node-8
    working_directory: ~/tunnckocore-monorepo
    docker:
      - image: circleci/node:8
  node-10: &node-10
    working_directory: ~/tunnckocore-monorepo
    docker:
      - image: circleci/node:10
  restore-cache: &restore-cache
      keys:
        - v1-monorepo-{{ checksum "yarn.lock" }}-{{ checksum ".circleci/config.yml" }}
        - v1-monorepo-{{ checksum "yarn.lock" }}
        - v1-monorepo-
  save-cache: &save-cache
    key: v1-monorepo-{{ checksum "yarn.lock" }}-{{ checksum ".circleci/config.yml" }}
    paths:
      - ~/.cache/yarn
      - ~/.cache/yarn-packages-cache
      - node_modules
  attach-ws: &attach-ws
    at: ~/tunnckocore-monorepo
  yarn: &yarn
    name: Install Dependencies
    command: yarn install --prefer-offline || yarn install
  test: &test
    # TODO: remove the `--all` flag
    name: Run Tests
    command: yarn run test --coverage --all
  lint: &lint
    # TODO: remove the `--all` flag
    name: Lint Packages
    command: yarn run lint --all
  git: &git
    name: Configure git settings
    command: |-
      git config --global user.email "mameto2011@gmail.com"
      git config --global user.name "Charlike Mike Reagent"
  npm: &npm
    name: Configure npm settings
    command: |-
      echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ./.npmrc

jobs:
  install:
    <<: *node-8
    steps:
      - checkout
      - restore_cache: *restore-cache
      - run: *yarn
      - save_cache: *save-cache
      - persist_to_workspace:
          root: .
          paths:
            - .
  test-node-8:
    <<: *node-8
    steps:
      - attach_workspace: *attach-ws
      - run: *test
  test-node-10:
    <<: *node-10
    steps:
      - attach_workspace: *attach-ws
      - run: *test
      - run:
          name: Send CodeCov Results
          command: bash <(curl -s https://codecov.io/bash)
  lint:
    <<: *node-10
    steps:
      - attach_workspace: *attach-ws
      - run: *lint
  typecheck:
    <<: *node-10
    steps:
      - attach_workspace: *attach-ws
      - run:
          name: Type checking with TypeScript
          command: yarn run tscheck
  build:
    <<: *node-10
    steps:
      - attach_workspace: *attach-ws
      - run: # TODO: use jest-runner-babel soon, instead of lerna exec --parallel
          name: Build production files
          command: yarn run build
  deploy:
    <<: *node-10
    steps:
      - attach_workspace: *attach-ws
      - add_ssh_keys: # User machine's key fingerprint (CircleCI User Key)
          fingerprints:
            - "d1:7e:2a:2d:2f:07:8f:d9:b5:f6:41:57:77:03:e1:f0"
      - run: *git
      - run: *npm
      - run:
          name: Publish to npm and GitHub
          command: yarn run release --yes


workflows:
  version: 2
  automation:
    jobs:
      #                    typecheck
      # install -> lint -> test node 8  -> build -> deploy (only on master)
      #                    test node 10
      - install
      - lint:
          requires:
            - install
      - typecheck:
          requires:
            - lint
      - test-node-8:
          requires:
            - lint
      - test-node-10:
          requires:
            - lint
      - build:
          requires:
            - typecheck
            - test-node-8
            - test-node-10
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
