# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1

references:
  node-8: &node-8
    working_directory: ~/tunnckocore-monorepo
    docker:
      - image: circleci/node:8
  node-10: &node-10
    working_directory: ~/tunnckocore-monorepo
    docker:
      - image: circleci/node:10
  restore-cache: &restore-cache
      keys:
        - v2-monorepo-{{ checksum "yarn.lock" }}-{{ checksum ".circleci/config.yml" }}
        - v2-monorepo-{{ checksum "yarn.lock" }}
        - v2-monorepo-
  save-cache: &save-cache
    key: v2-monorepo-{{ checksum "yarn.lock" }}-{{ checksum ".circleci/config.yml" }}
    paths:
      - ~/.ssh
      - ~/.gitconfig
      - ~/.cache/yarn
      - ~/.cache/yarn-packages-cache
      - node_modules
  attach-ws: &attach-ws
    at: ~/tunnckocore-monorepo
  yarn: &yarn
    name: Install Dependencies
    command: yarn install --prefer-offline || yarn install
  test: &test
    # TODO: add the `--all` flag when needed, to overwrite the --onlyChanged
    name: Run Tests
    command: yarn run test:ci
  lint: &lint
    # TODO: add the `--all` flag when needed, to overwrite the --onlyChanged
    name: Lint Packages
    command: yarn run lint:ci
  git: &git
    name: Configure git settings
    command: |-
      git config --global user.email "mameto2011@gmail.com"
      git config --global user.name "Charlike Mike Reagent"
      git config --global user.signingkey "$GIT_SIGNING_KEY"
      git config --global commit.gpgsign true
  npm: &npm
    name: Configure npm settings
    command: |-
      echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ./.npmrc

jobs:
  install:
    <<: *node-8
    steps:
      - checkout
      - run: *yarn
      - run: yarn build:execa
      - run: *git
      - save_cache: *save-cache
      - persist_to_workspace:
          root: .
          paths:
            - .
  test-node-8:
    <<: *node-8
    steps:
      - attach_workspace: *attach-ws
      - run: *test
  test-node-10:
    <<: *node-10
    steps:
      - attach_workspace: *attach-ws
      - run: *test
      - run:
          name: Send CodeCov Results
          command: bash <(curl -s https://codecov.io/bash)
  lint:
    <<: *node-10
    steps:
      - attach_workspace: *attach-ws
      - run: *lint
  typecheck:
    <<: *node-10
    steps:
      - attach_workspace: *attach-ws
      - run:
          name: Type checking with TypeScript
          command: yarn run type:check
  build:
    <<: *node-10
    steps:
      - attach_workspace: *attach-ws
      - run: # TODO: use jest-runner-babel soon, instead of lerna exec --parallel
          name: Build production files
          command: yarn run build
  deploy:
    <<: *node-10
    steps:
      - attach_workspace: *attach-ws
      - restore_cache: *restore-cache
      - add_ssh_keys: # User machine's key fingerprint (CircleCI User Key)
          fingerprints:
            # Fingerprint of the special SSH key for CircleCI
            - "65:dd:e6:57:21:52:c4:c6:c8:59:b4:56:f3:65:ec:b4"
      # - run:
      #     name: KeyScan GitHub
      #     command: ssh-keyscan -H github.com >> ~/.ssh/known_hosts
      - run: *npm
      - run:
          name: Publish to npm and GitHub
          command: yarn run release --yes


workflows:
  version: 2
  automation:
    jobs:
      #                    typecheck
      # install -> lint -> test node 8  -> build -> deploy (only on master)
      #                    test node 10
      - install
      - lint:
          requires:
            - install
      - typecheck:
          requires:
            - lint
      - test-node-8:
          requires:
            - lint
      - test-node-10:
          requires:
            - lint
      - build:
          requires:
            - typecheck
            - test-node-8
            - test-node-10
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
